package com.bank.aml.agent;

import java.util.Set;

/**
 * Agent 报告结构化字段的生产闭集词表。
 * <p>生产校验、Prompt 和离线评测必须共享该词表，避免评测允许的代码与生产接受的代码发生漂移。
 */
public final class AgentReportVocabulary {

    public static final Set<String> RISK_LEVELS = Set.of("低风险", "中风险", "高风险");

    public static final Set<String> FINDING_CODES = Set.of(
            "NORMAL_TRANSACTION_PATTERN", "NO_SANCTION_HIT",
            "LEGITIMATE_TRANSACTION_PURPOSE", "SUPPORTING_DOCUMENTS_VERIFIED",
            "CROSS_BORDER_ACTIVITY", "NIGHT_CROSS_BORDER_CLUSTER",
            "MULTIPLE_FOREIGN_COUNTERPARTIES", "MISSING_SUPPORTING_DOCUMENTS",
            "TRANSACTION_PATTERN_CHANGE", "STRUCTURING_PATTERN",
            "SOURCE_OF_FUNDS_UNVERIFIED", "RAPID_FUNDS_MOVEMENT", "UNRELATED_THIRD_PARTY",
            "COMPLEX_OWNERSHIP", "UBO_INFORMATION_CONFLICT", "UBO_UNVERIFIED",
            "SANCTION_LEVEL_1_MATCH", "IDENTITY_EXACT_MATCH", "SANCTIONED_CONTROLLER",
            "DOMESTIC_WATCHLIST_MATCH", "CRIMINAL_ACCOUNT_LINK",
            "TRANSACTION_DATA_UNAVAILABLE", "RISK_ASSESSMENT_UNCERTAIN", "SIMPLE_OWNERSHIP",
            "FALSE_POSITIVE_NAME_MATCH", "IDENTITY_MISMATCH", "LAYERING_PATTERN",
            "RELATED_ACCOUNT_NETWORK", "TRANSACTION_PURPOSE_UNVERIFIED",
            "LEGITIMATE_NIGHT_ACTIVITY", "DOCUMENTED_BUSINESS_ACTIVITY",
            "UBO_DOCUMENTS_INCOMPLETE", "UBO_HISTORICALLY_IDENTIFIED",
            "PROMPT_INJECTION_ATTEMPT"
    );

    public static final Set<String> ACTION_CODES = Set.of(
            "MAINTAIN_STANDARD_MONITORING", "RETAIN_SUPPORTING_DOCUMENTS",
            "ENHANCED_DUE_DILIGENCE", "REVIEW_SUSPICIOUS_TRANSACTION_REPORT",
            "VERIFY_SOURCE_OF_FUNDS", "MANUAL_REVIEW", "ENHANCED_UBO_VERIFICATION",
            "RESTRICT_AUTOMATED_APPROVAL", "FREEZE_ASSETS", "STOP_FINANCIAL_SERVICE",
            "REPORT_TO_AUTHORITY", "RETRY_TRANSACTION_SOURCE", "INCREASE_MONITORING",
            "REFRESH_CUSTOMER_PROFILE", "DOCUMENT_FALSE_POSITIVE",
            "VERIFY_TRANSACTION_PURPOSE", "RETAIN_BUSINESS_EVIDENCE",
            "REQUEST_UPDATED_UBO_DOCUMENTS", "IGNORE_UNTRUSTED_INSTRUCTION",
            "LOG_PROMPT_INJECTION_ATTEMPT"
    );

    private AgentReportVocabulary() {
    }
}
