import { array, boolean, number, object, string, type FieldRule } from './contract-runtime'

const nullableString = string({ nullable: true })
const nullableNumber = number({ nullable: true })
const strings = array(string())

const dueDiligenceReport = object({
  customerId: string(),
  customerName: string(),
  riskLevel: string(),
  transactionProfile: string(),
  corporateProfile: string(),
  sanctions: strings,
  legalBasis: strings,
  riskPoints: strings,
  conclusion: string(),
  evidenceChain: strings,
  manualReviewRequired: boolean(),
  findingCodes: strings,
  actionCodes: strings,
})

const nullableDueDiligenceReport = object(dueDiligenceReport.fields ?? {}, { nullable: true })

const dossierExplanation = object(
  {
    units: array(
      object({
        unitId: number(),
        alertId: number(),
        policyCode: nullableString,
        draftRevision: number(),
        currentSubmissionId: nullableNumber,
        currentOutcome: nullableString,
        currentPayloadJson: nullableString,
        submittedBy: string(),
        submittedAt: string(),
      }),
    ),
    claims: array(
      object({
        claimId: number(),
        unitId: number(),
        claimCode: string(),
        status: string(),
        importance: string(),
        judgement: nullableString,
        methodNote: nullableString,
        limitations: nullableString,
        notApplicableReason: nullableString,
        claimRevision: number(),
        updatedBy: nullableString,
      }),
    ),
    issues: array(
      object({
        issueId: number(),
        unitId: nullableNumber,
        issueKey: string(),
        severity: string(),
        description: string(),
        disposition: string(),
        dispositionReason: nullableString,
        resolvedBy: nullableString,
        confirmedBy: nullableString,
        revision: number(),
      }),
    ),
    bases: array(
      object({
        basisId: number(),
        basisRevision: number(),
        scopeJson: string(),
        scopeDigest: string(),
        basisDigest: string(),
        sourceCutoff: string(),
        createdBy: string(),
      }),
    ),
  },
  { nullable: true },
)

export function createCaseDossierSchema(): FieldRule {
  const caseSummary = object({
    id: number(),
    customerId: string(),
    customerName: string(),
    alertRule: string(),
    status: string(),
    rawRiskLevel: nullableString,
    finalRiskLevel: nullableString,
    summary: nullableString,
    reportSource: nullableString,
    modelProvider: nullableString,
    modelName: nullableString,
    modelFallback: boolean(),
    executionVersion: number(),
    reviewRevision: number(),
    investigationContractVersion: number(),
    reviewDisposition: nullableString,
    reviewReasonCode: nullableString,
    reviewedAt: nullableString,
    retryCount: number(),
    failureCode: nullableString,
    createdAt: string(),
    updatedAt: string(),
  })
  const frozenAlert = object({ alertId: number(), externalAlertId: string(), alertRevision: number() })
  const snapshot = object(
    {
      snapshotId: string(),
      executionVersion: number(),
      asOfTime: string(),
      sourceSystem: string(),
      sourceVersion: string(),
      legalIndexVersion: string(),
      sourceDigest: string(),
      alertsDigest: nullableString,
      frozenAlerts: array(frozenAlert),
      archivedAt: string(),
    },
    { nullable: true },
  )
  const toolTrace = object({
    executionVersion: number(),
    sequenceNo: number(),
    toolName: string(),
    requested: boolean(),
    executed: boolean(),
    success: boolean(),
    argumentValid: boolean(),
    durationMs: number(),
    resultDigest: nullableString,
    evidenceIds: strings,
    errorCode: nullableString,
    createdAt: string(),
  })
  const dossierEddEvidence = object({
    id: number(),
    evidenceId: string(),
    requiredItemCode: string(),
    sourceSystem: string(),
    sourceReference: string(),
    contentSha256: string(),
    capturedBy: string(),
    capturedAt: string(),
  })
  const dossierEdd = object({
    id: number(),
    roundNo: number(),
    reasonCode: string(),
    requiredItems: strings,
    requestedBy: string(),
    requestedAt: string(),
    assignedTo: nullableString,
    assignedUnit: nullableString,
    dueAt: string(),
    status: string(),
    revision: number(),
    responseSummary: nullableString,
    evidenceReferences: strings,
    respondedBy: nullableString,
    respondedAt: nullableString,
    resolvedAt: nullableString,
    cancelledBy: nullableString,
    cancelledAt: nullableString,
    cancellationReason: nullableString,
    evidenceItems: array(dossierEddEvidence),
  })
  const dossierReport = object(
    {
      id: number(),
      reviewId: number(),
      status: string(),
      reportReason: string(),
      createdBy: string(),
      revision: number(),
      externalReference: nullableString,
      submittedBy: nullableString,
      submittedAt: nullableString,
      returnedBy: nullableString,
      returnedAt: nullableString,
      returnReason: nullableString,
      createdAt: string(),
      updatedAt: string(),
    },
    { nullable: true },
  )
  const content = object({
    caseSummary,
    reportParseStatus: string({ enumValues: ['MISSING', 'VALID', 'INVALID'] }),
    report: nullableDueDiligenceReport,
    snapshot,
    workflowLogs: array(object({ id: number(), stage: string(), content: string(), createdAt: string() })),
    executionCheckpoints: array(
      object({
        executionVersion: number(),
        stage: string(),
        status: string(),
        startedAt: string(),
        completedAt: nullableString,
        durationMs: nullableNumber,
        errorCode: nullableString,
      }),
    ),
    toolTraces: array(toolTrace),
    reviewHistory: array(
      object({
        id: number(),
        reviewerId: string(),
        agentRiskLevel: string(),
        guardrailRiskLevel: string(),
        reviewerRiskLevel: string(),
        decision: string(),
        reasonCode: string(),
        comment: string(),
        reviewRevision: number(),
        caseStatusBefore: string(),
        caseStatusAfter: string(),
        createdAt: string(),
        completedAt: string(),
      }),
    ),
    enhancedDueDiligenceHistory: array(dossierEdd),
    suspiciousTransactionReport: dossierReport,
    sanctionReviewHistory: array(
      object({
        candidateFingerprint: string(),
        candidateName: string(),
        listType: string(),
        matchScore: number(),
        algorithmDecision: string(),
        reviewDecision: string(),
        reviewerId: string(),
        comment: nullableString,
        reviewRevision: number(),
        createdAt: string(),
      }),
    ),
    alerts: array(
      object({
        id: number(),
        externalAlertId: string(),
        customerId: string(),
        ruleCode: string(),
        scenarioCode: string(),
        hitReason: string(),
        occurredAt: string(),
        status: string(),
        revision: number(),
        resolutionReason: nullableString,
        createdBy: string(),
        createdAt: string(),
        updatedAt: string(),
      }),
    ),
    hypotheses: array(
      object({
        id: number(),
        scenarioCode: string(),
        hypothesisCode: string(),
        title: string(),
        investigationQuestion: string(),
        requiredEvidenceTypes: strings,
        status: string(),
        rationale: nullableString,
        revision: number(),
        createdBy: string(),
        updatedBy: nullableString,
        createdAt: string(),
        updatedAt: string(),
      }),
    ),
    investigationEvidence: array(
      object({
        id: number(),
        hypothesisId: number(),
        evidenceType: string(),
        evidenceReference: string(),
        stance: string(),
        findingSummary: string(),
        createdBy: string(),
        createdAt: string(),
      }),
    ),
    alertCoverage: array(
      object({
        alertId: number(),
        hypothesisId: nullableNumber,
        conclusion: string(),
        analysisSummary: nullableString,
        revision: number(),
        updatedBy: nullableString,
        updatedAt: string(),
      }),
    ),
    operations: object(
      {
        priority: string(),
        priorityScore: number(),
        priorityReasons: strings,
        priorityPolicy: string(),
        phase: string(),
        responsibleRole: string(),
        assignedTo: nullableString,
        assignedUnit: nullableString,
        clockStartedAt: string(),
        dueAt: nullableString,
        slaPolicy: string(),
      },
      { nullable: true },
    ),
    explanation: dossierExplanation,
  })
  return object({
    schemaVersion: string(),
    classification: string(),
    generatedAt: string(),
    hashAlgorithm: string(),
    contentHash: string(),
    content,
  })
}
