import { array, boolean, number, object, record, string, type FieldRule } from './contract-runtime'
import { responseSchemas } from './response-schema-catalog'
import {
  agentEvalReportSchema,
  refundReversalSchema,
  sanctionScreeningSchema,
  transactionWindowsSchema,
  verificationSchema,
} from './specialized-response-schemas'

interface RouteContract {
  method: string
  path: RegExp
  name: string
  schema: FieldRule
}

const {
  nullableString,
  nullableNumber,
  strings,
  caseItem,
  customer,
  customerAdmin,
  page,
  operation,
  alert,
  evidence,
  hypothesis,
  coverage,
  investigation,
  assistantConversation,
  assistantMessage,
  manualReview,
  edd,
  suspiciousReport,
  explanationUnit,
  explanationIssue,
  explanationEvidence,
  explanationWorkspace,
  toolTrace,
  issueReview,
  caseDossier,
  agentEvalDataset,
} = responseSchemas

export const routes: RouteContract[] = [
  {
    method: 'get',
    path: /^\/auth\/csrf$/,
    name: 'CsrfBootstrap',
    schema: object({ headerName: string(), parameterName: string() }),
  },
  {
    method: 'post',
    path: /^\/auth\/login$/,
    name: 'AuthenticatedUser',
    schema: object({ username: string(), role: string() }),
  },
  {
    method: 'get',
    path: /^\/auth\/me$/,
    name: 'AuthenticatedUser',
    schema: object({ username: string(), role: string() }),
  },
  { method: 'post', path: /^\/auth\/logout$/, name: 'Logout', schema: object({ ok: boolean() }) },
  { method: 'get', path: /^\/cases$/, name: 'CasePage', schema: page(caseItem) },
  { method: 'post', path: /^\/cases$/, name: 'CaseItem', schema: caseItem },
  {
    method: 'get',
    path: /^\/cases\/stats$/,
    name: 'CaseStats',
    schema: object({
      total: number(),
      pending: number(),
      running: number(),
      hold: number(),
      reportPending: number(),
      done: number(),
      failed: number(),
    }),
  },
  { method: 'get', path: /^\/cases\/customers$/, name: 'CustomerList', schema: array(customer) },
  { method: 'get', path: /^\/cases\/\d+$/, name: 'CaseItem', schema: caseItem },
  { method: 'post', path: /^\/cases\/\d+\/(?:process|retry)$/, name: 'CaseItem', schema: caseItem },
  {
    method: 'get',
    path: /^\/cases\/\d+\/logs$/,
    name: 'CaseLogList',
    schema: array(object({ id: number(), stage: string(), content: string() })),
  },
  { method: 'get', path: /^\/cases\/\d+\/tools$/, name: 'ToolTraceList', schema: array(toolTrace) },
  { method: 'get', path: /^\/case-operations$/, name: 'CaseOperationsList', schema: array(operation) },
  { method: 'get', path: /^\/case-operations\/\d+$/, name: 'CaseOperations', schema: operation },
  { method: 'get', path: /^\/admin\/customers$/, name: 'CustomerAdminPage', schema: page(customerAdmin) },
  { method: 'post', path: /^\/admin\/customers$/, name: 'CustomerAdmin', schema: customerAdmin },
  { method: 'get', path: /^\/admin\/customers\/\d+$/, name: 'CustomerAdmin', schema: customerAdmin },
  { method: 'put', path: /^\/admin\/customers\/\d+(?:\/status)?$/, name: 'CustomerAdmin', schema: customerAdmin },
  {
    method: 'post',
    path: /^\/admin\/customers\/import$/,
    name: 'CustomerImport',
    schema: object({ total: number(), success: number(), failed: number(), errors: strings }),
  },
  {
    method: 'get',
    path: /^\/assistant\/status$/,
    name: 'AssistantStatus',
    schema: object({ enabled: boolean(), maxMessageChars: number() }),
  },
  {
    method: 'post',
    path: /^\/admin\/customers\/\d+\/assistant\/conversations$/,
    name: 'AssistantConversation',
    schema: assistantConversation,
  },
  {
    method: 'get',
    path: /^\/admin\/customers\/\d+\/assistant\/conversations$/,
    name: 'AssistantConversationPage',
    schema: page(assistantConversation),
  },
  {
    method: 'get',
    path: /^\/assistant\/conversations\/[^/]+\/messages$/,
    name: 'AssistantMessageList',
    schema: array(assistantMessage),
  },
  {
    method: 'post',
    path: /^\/assistant\/conversations\/[^/]+\/messages$/,
    name: 'AssistantAcceptedRun',
    schema: object({
      runId: string(),
      userMessageId: string(),
      assistantMessageId: string(),
      status: string({ enumValues: ['ACCEPTED'] }),
      idempotentReplay: boolean(),
    }),
  },
  { method: 'get', path: /^\/alerts$/, name: 'AlertList', schema: array(alert) },
  { method: 'post', path: /^\/alerts$/, name: 'Alert', schema: alert },
  { method: 'get', path: /^\/alerts\/\d+\/candidate-cases$/, name: 'CandidateCaseList', schema: array(caseItem) },
  { method: 'post', path: /^\/alerts\/\d+\/(?:create-case|split)$/, name: 'CaseItem', schema: caseItem },
  { method: 'post', path: /^\/alerts\/\d+\/(?:link|duplicate)$/, name: 'Alert', schema: alert },
  { method: 'get', path: /^\/cases\/\d+\/alerts$/, name: 'AlertList', schema: array(alert) },
  { method: 'get', path: /^\/cases\/\d+\/investigation$/, name: 'CaseInvestigation', schema: investigation },
  {
    method: 'get',
    path: /^\/cases\/\d+\/investigation\/playbooks$/,
    name: 'PlaybookList',
    schema: array(
      object({
        code: string(),
        name: string(),
        defaultHypothesisCode: string(),
        defaultHypothesisTitle: string(),
        investigationQuestion: string(),
        requiredEvidenceTypes: strings,
        escalationFocus: string(),
      }),
    ),
  },
  {
    method: 'get',
    path: /^\/cases\/\d+\/investigation\/transaction-windows$/,
    name: 'TransactionWindows',
    schema: transactionWindowsSchema,
  },
  {
    method: 'post',
    path: /^\/cases\/\d+\/investigation\/hypotheses\/\d+\/evidence$/,
    name: 'InvestigationEvidence',
    schema: evidence,
  },
  {
    method: 'put',
    path: /^\/cases\/\d+\/investigation\/hypotheses\/\d+$/,
    name: 'InvestigationHypothesis',
    schema: hypothesis,
  },
  {
    method: 'put',
    path: /^\/cases\/\d+\/investigation\/alerts\/\d+\/coverage$/,
    name: 'AlertCoverage',
    schema: coverage,
  },
  {
    method: 'get',
    path: /^\/sanctions\/screen\/[^/]+$/,
    name: 'SanctionScreening',
    schema: sanctionScreeningSchema,
  },
  {
    method: 'post',
    path: /^\/sanctions\/screen\/[^/]+\/review$/,
    name: 'SanctionScreening',
    schema: sanctionScreeningSchema,
  },
  {
    method: 'get',
    path: /^\/cases\/\d+\/dossier$/,
    name: 'CaseDossier',
    schema: caseDossier,
  },
  { method: 'get', path: /^\/reviews\/pending$/, name: 'PendingReviews', schema: array(caseItem) },
  { method: 'get', path: /^\/reviews\/\d+$/, name: 'ReviewList', schema: array(manualReview) },
  { method: 'post', path: /^\/reviews\/\d+$/, name: 'ManualReview', schema: manualReview },
  {
    method: 'post',
    path: /^\/reviews\/\d+\/prechecks$/,
    name: 'ReviewPrecheck',
    schema: object({
      caseId: number(),
      caseStatus: string(),
      caseFactsEpoch: number(),
      reviewRevision: number(),
      decision: nullableString,
      tokenCurrent: boolean(),
      tokenProblem: nullableString,
      continuationPlanChecks: array(
        object({
          originRequestId: nullableNumber,
          problem: nullableString,
          originRound: nullableNumber,
          assignedTo: nullableString,
          dueAt: nullableString,
          completionStandardPresent: boolean(),
          standardProblem: nullableString,
        }),
      ),
      uncoveredDecisionSupportTasks: array(number()),
      canExclude: boolean({ nullable: true }),
      canConfirm: boolean({ nullable: true }),
      excludeBlockers: array(string(), { nullable: true }),
      confirmBlockers: array(string(), { nullable: true }),
      simulatedObligationCoverage: object({ covered: strings, uncovered: strings }, { nullable: true }),
    }),
  },
  {
    method: 'get',
    path: /^\/reviews\/stats$/,
    name: 'ReviewStats',
    schema: object({
      reviewedCount: number(),
      agreementRate: number(),
      confirmedSuspiciousCount: number(),
      falsePositiveCount: number(),
      eddRequestedCount: number(),
      approvedCount: number(),
      rejectedCount: number(),
      escalatedCount: number(),
    }),
  },
  { method: 'get', path: /^\/cases\/\d+\/edd$/, name: 'EddList', schema: array(edd) },
  { method: 'get', path: /^\/edd\/tasks$/, name: 'EddList', schema: array(edd) },
  {
    method: 'get',
    path: /^\/edd\/assignees$/,
    name: 'AssigneeList',
    schema: array(object({ username: string(), role: string() })),
  },
  { method: 'post', path: /^\/cases\/\d+\/edd\/\d+\/(?:submit|cancel)$/, name: 'Edd', schema: edd },
  { method: 'get', path: /^\/reports\/pending$/, name: 'ReportList', schema: array(suspiciousReport) },
  { method: 'get', path: /^\/reports\/\d+$/, name: 'Report', schema: suspiciousReport },
  { method: 'post', path: /^\/reports\/\d+\/(?:submit|return)$/, name: 'Report', schema: suspiciousReport },
  {
    method: 'get',
    path: /^\/cases\/\d+\/investigation\/explanation-workspace$/,
    name: 'ExplanationWorkspace',
    schema: explanationWorkspace,
  },
  {
    method: 'post',
    path: /^\/cases\/\d+\/investigation\/evidence\/captures$/,
    name: 'ExplanationEvidence',
    schema: explanationEvidence,
  },
  {
    method: 'post',
    path: /^\/cases\/\d+\/investigation\/evidence\/\d+\/verifications$/,
    name: 'ExplanationVerification',
    schema: verificationSchema,
  },
  {
    method: 'put',
    path: /^\/cases\/\d+\/investigation\/units\/\d+\/draft$/,
    name: 'ExplanationUnit',
    schema: explanationUnit,
  },
  {
    method: 'post',
    path: /^\/cases\/\d+\/investigation\/units\/\d+\/submissions$/,
    name: 'ExplanationSubmission',
    schema: object({
      submissionId: number(),
      unitId: number(),
      submissionNo: number(),
      outcome: string(),
      state: string(),
      hypothesisAggregate: string(),
      reviewBasisToken: string(),
      messages: strings,
    }),
  },
  {
    method: 'post',
    path: /^\/cases\/\d+\/investigation\/units\/\d+\/amendments$/,
    name: 'ExplanationUnit',
    schema: explanationUnit,
  },
  {
    method: 'post',
    path: /^\/cases\/\d+\/investigation\/issues\/\d+\/dispositions$/,
    name: 'ExplanationIssue',
    schema: explanationIssue,
  },
  {
    method: 'post',
    path: /^\/cases\/\d+\/investigation\/issues\/\d+\/downgrade-proposals$/,
    name: 'IssueDowngradeProposal',
    schema: issueReview,
  },
  {
    method: 'post',
    path: /^\/cases\/\d+\/investigation\/downgrade-proposals\/\d+\/confirmations$/,
    name: 'ExplanationIssue',
    schema: explanationIssue,
  },
  {
    method: 'post',
    path: /^\/cases\/\d+\/investigation\/downgrade-proposals\/\d+\/rejections$/,
    name: 'IssueDowngradeRejection',
    schema: issueReview,
  },
  {
    method: 'post',
    path: /^\/cases\/\d+\/investigation\/(?:edd-proposals|edd-tasks\/\d+\/completion)$/,
    name: 'ExplanationEdd',
    schema: edd,
  },
  {
    method: 'get',
    path: /^\/cases\/\d+\/investigation\/units\/\d+\/next-actions$/,
    name: 'NextActionList',
    schema: array(
      object({
        priority: number(),
        category: string(),
        relatedClaimCode: nullableString,
        relatedIssueKey: nullableString,
        missingFact: string(),
        suggestedSource: string(),
        suggestedAction: string(),
        whatItCanChange: string(),
        alternative: string(),
      }),
    ),
  },
  {
    method: 'get',
    path: /^\/cases\/\d+\/investigation\/units\/\d+\/repeated-evidence$/,
    name: 'RepeatedEvidence',
    schema: object({ repeated: boolean() }),
  },
  {
    method: 'get',
    path: /^\/cases\/\d+\/investigation\/review-basis$/,
    name: 'ReviewBasis',
    schema: object({
      caseId: number(),
      caseFactsEpoch: number(),
      reviewBasisToken: string(),
      reviewerIndependent: boolean(),
      canExclude: boolean(),
      canConfirm: boolean(),
      confirmBlockers: strings,
      excludeBlockers: strings,
      adoptedUnits: array(explanationUnit),
      openIssues: array(explanationIssue),
      unitOutcomes: record(string()),
    }),
  },
  {
    method: 'post',
    path: /^\/cases\/\d+\/refund-events$/,
    name: 'RefundRegistration',
    schema: object({
      eventId: number(),
      idempotentReplay: boolean(),
      unallocatedAmount: string(),
      currency: string(),
      eventStatus: string({ enumValues: ['REQUESTED', 'POSTED', 'REVERSED'] }),
    }),
  },
  {
    method: 'get',
    path: /^\/cases\/\d+\/refund-events\/ledger$/,
    name: 'RefundLedger',
    schema: object({
      originalByTransaction: record(string()),
      refundedByTransaction: record(string()),
      pendingRefundByTransaction: record(string()),
      totalOriginal: string(),
      totalRefunded: string(),
      totalPendingRefund: string(),
      totalRetained: string(),
      currency: string(),
      overAllocations: record(string()),
    }),
  },
  {
    method: 'post',
    path: /^\/cases\/\d+\/refund-events\/authority-assessment$/,
    name: 'RefundAuthority',
    schema: object({ admissible: boolean(), blockerCode: nullableString, explanation: string() }),
  },
  {
    method: 'post',
    path: /^\/cases\/\d+\/refund-events\/reversals$/,
    name: 'RefundReversal',
    schema: refundReversalSchema,
  },
  { method: 'post', path: /^\/eval\/agent\/dev$/, name: 'AgentEval', schema: agentEvalReportSchema },
  {
    method: 'get',
    path: /^\/eval\/agent\/status$/,
    name: 'AgentEvalStatus',
    schema: object({
      ready: boolean(),
      datasetReady: boolean(),
      enabledSplit: string({ enumValues: ['DEV'] }),
      dataset: agentEvalDataset,
      message: string(),
    }),
  },
  {
    method: 'get',
    path: /^\/eval\/agent\/dataset$/,
    name: 'AgentEvalDataset',
    schema: agentEvalDataset,
  },
]
