<script setup lang="ts">
import { useCaseDetailViewController } from './CaseDetailView.controller'

defineOptions({ name: 'CaseDetailView' })

const props = defineProps<{ caseId: number }>()
const emit = defineEmits<{ back: []; 'open-case': [caseId: number] }>()
// @ts-expect-error 外置模板的引用不会进入 vue-tsc 的 noUnusedLocals 分析，但这些绑定均由模板消费。
const {
  Back,
  canEditInvestigation,
  canProcess,
  canRetry,
  canReviewSanctions,
  canSplitOnCase,
  canSubmitEdd,
  caseItem,
  caseOperations,
  coverageConclusionText,
  coverageFor,
  coverageGapFor,
  coverageGapText,
  decideInvestigationHypothesis,
  detailLoading,
  dossierLoading,
  Download,
  eddDialogOpen,
  eddEvidenceItems,
  eddHistoryLoadError,
  eddRequests,
  eddRequiredItemText,
  eddResponseSummary,
  eddSourceSystemOptions,
  eddStatusText,
  eddSubmitting,
  editAlertCoverage,
  evidenceDialogOpen,
  evidenceHypothesis,
  evidenceReference,
  evidenceStance,
  evidenceStanceText,
  evidenceSubmitting,
  evidenceSummary,
  evidenceType,
  evidenceTypeText,
  ExplanationWorkspace,
  fmtDateTime,
  formatAmount,
  formatEddRequiredItems,
  handleCandidateReview,
  handleDossierDownload,
  handleProcess,
  handleRetry,
  holdPhaseHint,
  hypothesisStatusText,
  investigation,
  investigationActionId,
  investigationLoadError,
  investigationScenarioText,
  investigationStale,
  isActive,
  isDone,
  legalBody,
  legalTitle,
  loadError,
  logOpen,
  logs,
  openEddResponse,
  openInvestigationEvidence,
  operationsPhaseText,
  operationsPriorityText,
  reconfirmAlertCoverage,
  RefreshRight,
  RefundPanel,
  reloadInvestigationFacts,
  report,
  reportStatusText,
  reportWorkflowLoadError,
  respondingEdd,
  retryLoad,
  returningReport,
  returnReportForCorrection,
  reviewDecisionLabel,
  reviewDispositionText,
  reviewHistory,
  reviewingFingerprint,
  reviewReasonText,
  riskMeta,
  sanctionScreening,
  screeningDecisionText,
  screeningLoading,
  screeningTagType,
  snapPrefix,
  splitCaseAlert,
  sseState,
  statusMeta,
  streamingText,
  submitEddResponse,
  submitInvestigationEvidence,
  suspiciousReport,
  toolTraces,
  transactionWindows,
  VideoPlay,
  workflowStages,
} = useCaseDetailViewController(props, emit)
</script>

<template src="./templates/CaseDetailView.template.html"></template>

<style scoped src="./styles/CaseDetailView.css"></style>
